# Site settings
title: Minhas análises
email: carlos.interaminense@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
  O que fiz em AD1..

url: "https://carlosinteraminense.github.io/minhas-analises/" # the base hostname & protocol for your site
github_username:  carlosinteraminense
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
